# add host to group 'just_created' with variable foo=42
- add_host: name={{ ip_from_do }} groups=just_created foo=42

# add a host with a non-standard port local to your machines
- add_host: name={{ new_ip }}:{{ new_port }}

# add a host alias that we reach through a tunnel
- add_host: hostname={{ new_ip }}
  ansible_ssh_host={{ inventory_hostname }}
  ansible_ssh_port={{ new_port }}
